import type { Content } from "./types";

const gh = (repo: string) => `https://github.com/Itsmedexexplorer/${repo}`;

// Bundled content. The site uses this until the studio saves its first version,
// and falls back to it whenever storage is unreachable.
export const DEFAULT_CONTENT: Content = {
  profile: {
    name: "Dhanesh Shetty",
    intro: "AI & Data Science student and co-founder of Nexa Tech. I build AI agents, apps and automations that people actually use.",
    verbs: ["thinks.", "sees.", "flies.", "ships."],
    focus: ["AI agents", "Mobile", "Robotics", "Automation"],
    location: "Kolhapur, India",
    email: "itsmedexexplorer@gmail.com",
    openTo: "Open to internships in AI, agent engineering and full-stack development.",
    building: "",
    github: "https://github.com/Itsmedexexplorer",
    githubUser: "Itsmedexexplorer",
    linkedin: "https://www.linkedin.com/in/dhanesh-shetty-222597353/",
  },
  projects: [
    {
      id: "camart",
      title: "CamArt",
      tag: "Mobile app",
      year: "2026",
      isNew: true,
      summary: "A camera that turns your day into stickers. Haptic shape dial, 13 filters, on-device subject lift and WhatsApp sticker packs.",
      problem: "Photo apps make you keep everything. I wanted one small, lovable thing per day.",
      built: "An Expo app with a haptic quarter-circle shape dial, Skia filters, ML Kit subject lift and a native Kotlin bridge for WhatsApp sticker packs.",
      outcome: "v1.0 released as a 64 MB Android APK with a demo reel.",
      stack: ["React Native", "Expo", "Skia", "Reanimated", "Kotlin"],
      shape: "clover",
      links: [
        { label: "Download APK", href: `${gh("CamArt")}/releases/latest` },
        { label: "GitHub", href: gh("CamArt") },
      ],
      media: { type: "video", src: "/media/camart-demo.mp4", poster: "/media/camart-poster.jpg" },
    },
    {
      id: "nidar",
      title: "NIDAR AirMouse",
      tag: "Autonomous drone",
      year: "2026",
      isNew: true,
      summary: "A GPS-denied quadcopter that searches a covered, damaged building on its own, maps it and tags survivors.",
      problem: "Search and rescue indoors, with no GPS, debris everywhere and no pilot.",
      built: "ROS 2 stack with LiDAR SLAM, Nav2 frontier exploration, a 30 Hz reactive collision shield and OpenCV survivor detection that stamps finds onto the map.",
      outcome: "Full autonomous missions in Gazebo: take off, explore a 15 × 15 m maze, tag survivors and land.",
      stack: ["ROS 2", "Nav2", "Gazebo", "MAVROS", "OpenCV", "Python"],
      shape: "drone",
      links: [],
    },
    {
      id: "shilpsetu",
      title: "ShilpSetu AI",
      tag: "Voice commerce",
      year: "2026",
      isNew: true,
      summary: "From craft to commerce in 60 seconds. Artisans turn a photo and a voice note into a priced, buyer-ready listing in their own language.",
      problem: "Typing-heavy marketplaces shut out the artisans who make the best work.",
      built: "A voice-first PWA in 6 Indian languages: AI background cleanup, listing writer, price advisor and an AI bargain coach for both sides.",
      outcome: "Live app with artisan, buyer and organisation roles and realtime listings.",
      stack: ["React 19", "TanStack Start", "Supabase", "Gemini"],
      shape: "vase",
      links: [
        { label: "Live app", href: "https://shilpsetu.lovable.app" },
        { label: "GitHub", href: gh("shilpsetu") },
      ],
    },
    {
      id: "toka",
      title: "TO'KA",
      tag: "Desktop AI companion",
      year: "2026",
      summary: "A floating desktop pet that is also an agent: it searches the web, runs commands, opens apps and remembers you.",
      problem: "Assistants hide in a browser tab you forget about.",
      built: "An Electron character with a ReAct tool router that works across LLM providers, an emotion engine, cursor-tracking eyes and a liquid-glass chat.",
      outcome: "Installs as a global `toka` command. Open source.",
      stack: ["Electron", "TypeScript", "LLMs", "ReAct"],
      shape: "pet",
      links: [{ label: "GitHub", href: gh("TOKA") }],
    },
    {
      id: "tera",
      title: "Tera",
      tag: "Voice agents",
      year: "2026",
      summary: "A platform to build, test and run AI voice agents for hotels, clinics and coaching centres, including Hindi and Hinglish.",
      problem: "Small businesses miss calls and leads, and voice AI platforms are closed and costly.",
      built: "Agent builder with system prompts and workflows, in-browser voice preview, outbound dialer simulation, call logs, analytics and billing.",
      outcome: "Open-source alternative to platforms like Vapi.",
      stack: ["React", "Express", "Gemini", "Recharts"],
      shape: "wave",
      links: [{ label: "GitHub", href: gh("Tera_agenticvoiceautomations") }],
    },
    {
      id: "wacrm",
      title: "WA CRM",
      tag: "Client solution",
      year: "2026",
      summary: "A WhatsApp-first CRM with AI reservation agents, pipelines, broadcasts and workflow automation.",
      problem: "Businesses run on WhatsApp but manage leads in their heads.",
      built: "Contacts, pipelines and broadcasts on the Meta WhatsApp API, with Gemini agents and n8n workflows on Supabase.",
      outcome: "Built for Nexa Tech clients. Not public.",
      stack: ["Supabase", "n8n", "Gemini", "Meta API"],
      shape: "chat",
      links: [],
    },
    {
      id: "kisanmitra",
      title: "KisanMitra AI",
      tag: "IoT + AI",
      year: "2026",
      summary: "A smart farming companion: field sensors stream soil and weather data, AI turns it into daily advice for farmers.",
      problem: "Small farmers decide on guesswork and lose yield, water and money.",
      built: "ESP32 sensor nodes for moisture, pH and NPK, AI crop advisory, voice in regional languages and a QR crop passport.",
      outcome: "Showcased at Makers Conclave 2026. Live on Vercel.",
      stack: ["ESP32", "Python", "React", "Supabase"],
      shape: "leaf",
      links: [
        { label: "Live demo", href: "https://kisan-mitra-ai-1.vercel.app/" },
        { label: "GitHub", href: gh("Kisanmitr") },
      ],
    },
    {
      id: "photoproof",
      title: "Photoproof",
      tag: "Mobile app",
      year: "2026",
      summary: "Offline-first field documentation: location-tagged photos grouped into reports and exported as PDF.",
      problem: "Inspections happen where there is no signal.",
      built: "Expo app with GPS and reverse-geocoded capture, SQLite storage, Zustand state and PDF export.",
      outcome: "Open source with a demo video.",
      stack: ["Expo", "SQLite", "Zustand", "Reanimated"],
      shape: "frames",
      links: [{ label: "GitHub", href: gh("Photoproof") }],
    },
    {
      id: "anya",
      title: "ANYA",
      tag: "Terminal AI",
      year: "2026",
      summary: "An async-first AI companion that lives in your terminal and helps you code, plan and get things done.",
      problem: "Developers leave the terminal every time they need AI.",
      built: "Multi-LLM backend (OpenAI, Claude, Gemini, Ollama), safe tool execution and two-layer memory on SQLite.",
      outcome: "Open source, installs with `uv tool install`.",
      stack: ["Python", "LLMs", "SQLite", "CLI"],
      shape: "terminal",
      links: [{ label: "GitHub", href: gh("ANYA") }],
    },
    {
      id: "linkedin-autopilot",
      title: "LinkedIn Autopilot",
      tag: "Automation",
      year: "2026",
      summary: "Send an idea to a Telegram bot, get a LinkedIn post in your voice, approve it in chat and it publishes itself.",
      problem: "Posting consistently takes hours every week.",
      built: "n8n pipeline: Telegram trigger, allowlist check, Gemini drafts, edit loop, LinkedIn API and a Google Sheets content memory.",
      outcome: "Runs my own content. Workflow is open source.",
      stack: ["n8n", "Gemini", "Telegram", "LinkedIn API"],
      shape: "network",
      links: [{ label: "GitHub", href: gh("Automation_Projects") }],
    },
  ],
  archive: [
    { title: "Innovation Hub 5.0", note: "Lab equipment requests with OTP pickup and returns. React, Express, Prisma." },
    { title: "RIKA", note: "A Python CLI companion with seven personas, memory and streaks.", href: gh("rika") },
    { title: "Retro Web Hunter", note: "A 2D canvas shooter ported to React.", href: gh("2d-shooter") },
    { title: "Semantic search & RAG", note: "Document Q&A with LangChain, embeddings and vector search." },
    { title: "Nexa Tech", note: "Agency site for my AI automation studio.", href: "https://www.nexa-tech.in/" },
    { title: "DSA × LeetCode", note: "Daily pattern practice in C++.", href: gh("DSA-x-Leetcodeproblems") },
  ],
  log: [
    { date: "Oct 2026", title: "CamArt v1.0", note: "Released the sticker camera with an APK and demo reel." },
    { date: "Sep 2026", title: "NIDAR AirMouse", note: "Autonomous search, mapping and survivor tagging in ROS 2." },
    { date: "Sep 2026", title: "ShilpSetu AI", note: "Voice-first commerce for artisans in 6 languages." },
    { date: "Aug 2026", title: "TO'KA", note: "An agentic desktop companion with an emotion engine." },
    { date: "Jul 2026", title: "Tera and KisanMitra AI", note: "A voice agent platform and an IoT farming system." },
    { date: "Apr 2026", title: "ANYA", note: "Terminal-native AI companion, open source." },
    { date: "Mar 2026", title: "LinkedIn Autopilot", note: "n8n content pipeline with approval in Telegram." },
    { date: "2025", title: "Co-founded Nexa Tech", note: "AI automation, agents and WhatsApp systems for businesses." },
  ],
  wins: [
    { label: "1st place", title: "Ideathon, Project Solvix" },
    { label: "President", title: "ADSA, AI & Data Science Student Association" },
    { label: "Multiple rounds cleared", title: "Smart India Hackathon" },
    { label: "Showcased", title: "Makers Conclave 2026" },
    { label: "Participant", title: "NASA Space Apps Challenge" },
    { label: "Co-founder", title: "Nexa Tech" },
  ],
  certs: [
    "OpenAI Academy × NxtWave · GenAI Buildathon",
    "Google for Startups · Prompt to Prototype",
    "Outskill · GenAI Mastermind",
    "NIAT · Text Embeddings in LLM Systems",
  ],
  skills: [
    { group: "Languages", items: ["Python", "TypeScript", "JavaScript", "C++", "SQL"] },
    { group: "AI", items: ["AI agents", "RAG", "Embeddings", "Prompt engineering", "LangChain"] },
    { group: "Apps", items: ["React", "Next.js", "React Native", "Expo", "Electron", "Three.js"] },
    { group: "Automation", items: ["n8n", "WhatsApp API", "Telegram bots", "API integration"] },
    { group: "Robotics", items: ["ROS 2", "Nav2", "Gazebo", "OpenCV"] },
    { group: "Data & cloud", items: ["Supabase", "PostgreSQL", "Docker", "Vercel", "Linux"] },
  ],
  faq: [
    { q: "Who is Dhanesh Shetty?", a: "Dhanesh Shetty is an AI & Data Science student at Sanjay Ghodawat University (NIAT) in Kolhapur, India, and the co-founder of Nexa Tech. He builds AI agents, mobile apps, autonomous drone software and business automations." },
    { q: "What does Dhanesh Shetty build?", a: "AI agents and voice agents, React Native and Expo mobile apps such as CamArt, ROS 2 autonomous drone software such as NIDAR AirMouse, WhatsApp and n8n automations, and full-stack web apps with Next.js." },
    { q: "What is his tech stack?", a: "Python, TypeScript, React, Next.js, React Native, Expo, Three.js, ROS 2, n8n, Supabase and PostgreSQL, with LLMs from OpenAI, Gemini and Claude for agents and RAG." },
    { q: "Is Dhanesh Shetty available for internships or projects?", a: "Yes. He is open to internships in AI, agent engineering and full-stack development, and takes on automation and AI projects through Nexa Tech. Email itsmedexexplorer@gmail.com." },
    { q: "What is Nexa Tech?", a: "Nexa Tech is the AI automation studio Dhanesh co-founded in 2025. It builds AI agents, WhatsApp CRMs, voice agents and workflow automation for businesses." },
    { q: "What is CamArt?", a: "CamArt is Dhanesh's Android camera app that turns everyday photos into stickers, with a haptic shape dial, 13 filters, on-device subject lift and WhatsApp sticker packs." },
  ],
  resumeUrl: "/resume.pdf",
  updatedAt: "2026-10-04T00:00:00.000Z",
};
